#include <cassert>
#include <iostream>
#include <map>
#include "Arduino.h"
#include "Wire.h"
#include "ConfigStorage.h"
#define private public
#include "PressureController.h"
#undef private
#include "FanController.h"
#include "EventQueue.h"
#include "FingerController.h"
#include "AirflowController.h"
#include "NoteSequencer.h"
#include "InstrumentManager.h"
extern std::map<uint8_t,int> __analog_writes, __digital_writes, __analog_reads, __digital_reads;
static void resetCfg(){ memset(&cfg,0,sizeof(cfg)); cfg.numFingers=1; cfg.fingers[0].pcaChannel=0; cfg.fingers[0].closedAngle=90; cfg.fingers[0].direction=1; cfg.numPumps=1; cfg.pumpPins[0]=25; cfg.pumpPins[1]=26; cfg.pumpPins[2]=27; cfg.pumpMinPwm[0]=80; cfg.pumpMaxPwm[0]=200; cfg.pumpMinPwm[1]=90; cfg.pumpMaxPwm[1]=220; cfg.pumpMinPwm[2]=110; cfg.pumpMaxPwm[2]=255; cfg.motorType=MOTOR_TYPE_PWM; cfg.airMode=AIR_MODE_PUMP_VALVE; cfg.pumpCascadeThreshold=0; cfg.pumpStaggerMs=0; cfg.sensorType=SENSOR_TYPE_HALL_KY024; cfg.hallPin=36; cfg.hallThresholdLow=1000; cfg.hallThresholdHigh=2000; cfg.pidKp=10; cfg.pidKi=0; cfg.servoToSolenoidDelayMs=10; cfg.minNoteDurationMs=100; cfg.minNoteIntervalForValveCloseMs=0; cfg.airflowPcaChannel=10; cfg.solenoidPin=13; cfg.solenoidActivationTimeMs=50; cfg.solenoidPwmActivation=255; cfg.solenoidPwmHolding=128; cfg.servoAirflowOff=20; cfg.servoAirflowMin=60; cfg.servoAirflowMax=100; cfg.servoAngleOff=90; cfg.servoAngleMin=45; cfg.servoAngleMax=135; cfg.ccVolumeDefault=127; cfg.ccExpressionDefault=127; cfg.ccBreathDefault=127; cfg.ccBrightnessDefault=64; cfg.airVelocityResponse=100; strcpy(cfg.embouchure,"bec"); cfg.numNotes=3; cfg.notes[0].midiNote=60; cfg.notes[1].midiNote=61; cfg.notes[2].midiNote=62; cfg.notes[0].airflowMinPercent=0; cfg.notes[0].airflowMaxPercent=100; }
static int physical(int minv,int maxv,int logical){ return logical==0?0:minv+(maxv-minv)*logical/255; }
static void pressure_direct_pwm_once(){ resetCfg(); PressureController pc; for(int logical: {0,64,128,192,255}){ pc.setPumpPwm(logical); assert(__analog_writes[25]==physical(80,200,logical)); } cfg.numPumps=3; cfg.pumpCascadeThreshold=0; pc.setPumpPwm(128); assert(__analog_writes[25]==physical(80,200,128)); assert(__analog_writes[26]==physical(90,220,128)); assert(__analog_writes[27]==physical(110,255,128)); cfg.motorType=MOTOR_TYPE_ONOFF; pc.setPumpPwm(128); assert(__digital_writes[25]==HIGH); assert(__digital_writes[26]==HIGH); assert(__digital_writes[27]==HIGH); pc.setPumpPwm(0); assert(__digital_writes[25]==LOW); }
static void pressure_hall_pid_once_and_guards(){ resetCfg(); cfg.airMode=AIR_MODE_PUMP_RESERVOIR; PressureController pc; pc.begin(); pc.setTargetPercent(50); __test_millis=100; __analog_reads[36]=1000; pc.update(); assert(__analog_writes[25]==physical(80,200,127)); cfg.hallThresholdHigh=cfg.hallThresholdLow; __test_millis=200; pc.update(); assert(__analog_writes[25]>=0 && __analog_writes[25]<=255); cfg.numPumps=0; __test_millis=300; pc.update(); cfg.numPumps=9; cfg.pumpCascadeThreshold=100; validateAndNormalizeConfig(cfg,nullptr); assert(cfg.numPumps==MAX_PUMPS && cfg.pumpCascadeThreshold==99); }
static void event_queue_cases(){ EventQueue q(2); assert(q.isEmpty()); assert(q.enqueueScheduledEvent(EVENT_NOTE_ON,60,100,0)); assert(q.enqueueScheduledEvent(EVENT_NOTE_OFF,60,0,20)); assert(!q.enqueueScheduledEvent(EVENT_NOTE_ON,61,100,20)); q.dequeue(); q.dequeue(); assert(q.isEmpty() && q.getReferenceTime()==0); assert(q.enqueueScheduledEvent(EVENT_NOTE_ON,62,100,0xFFFFFFF0UL)); q.clear(); assert(q.isEmpty()); assert(q.enqueueScheduledEvent(EVENT_NOTE_ON,63,100,1)); }
static void note_sequencer_min_and_panic(){ resetCfg(); __test_millis=0; int fingerWrites=0, airWrites=0; FingerController fc([&](uint8_t,uint16_t,uint16_t){fingerWrites++;}); AirflowController ac([&](uint8_t,uint16_t,uint16_t){airWrites++;}); EventQueue q(8); NoteSequencer ns(q,fc,ac); ns.begin(); q.enqueueScheduledEvent(EVENT_NOTE_ON,60,100,0); ns.update(); assert(ns.getState()==STATE_POSITIONING && fingerWrites>0); __test_millis=10; ns.update(); assert(ns.getState()==STATE_PLAYING && ac.isValveOpen()); q.enqueueScheduledEvent(EVENT_NOTE_OFF,60,0,20); __test_millis=20; ns.update(); assert(ns.getState()==STATE_PLAYING); __test_millis=99; ns.update(); assert(ns.getState()==STATE_PLAYING); __test_millis=110; ns.update(); assert(ns.getState()==STATE_STOPPING); ns.stop(); assert(ns.getState()==STATE_IDLE && !ac.isValveOpen()); }

static void note_sequencer_monophonic_replacement(){ resetCfg(); cfg.minNoteDurationMs=100; cfg.minNoteIntervalForValveCloseMs=50; __test_millis=0; int fingerWrites=0; FingerController fc([&](uint8_t,uint16_t,uint16_t){fingerWrites++;}); AirflowController ac([&](uint8_t,uint16_t,uint16_t){}); EventQueue q(16); NoteSequencer ns(q,fc,ac); ns.begin(); q.enqueueScheduledEvent(EVENT_NOTE_ON,60,100,0); q.enqueueScheduledEvent(EVENT_NOTE_ON,62,100,0); q.enqueueScheduledEvent(EVENT_NOTE_OFF,60,0,0); q.enqueueScheduledEvent(EVENT_NOTE_OFF,62,0,0); ns.update(); assert(q.isEmpty()); assert(ns.getState()==STATE_IDLE); assert(fingerWrites>=2); ns.stop(); q.enqueueScheduledEvent(EVENT_NOTE_ON,60,100,1000); q.enqueueScheduledEvent(EVENT_NOTE_OFF,60,0,1010); q.enqueueScheduledEvent(EVENT_NOTE_ON,62,100,1010); __test_millis=1000; ns.update(); __test_millis=1010; ns.update(); assert(ns.getState()==STATE_POSITIONING); ns.stop(); q.enqueueScheduledEvent(EVENT_NOTE_ON,60,100,2000); q.enqueueScheduledEvent(EVENT_NOTE_ON,61,100,2000); q.enqueueScheduledEvent(EVENT_NOTE_ON,62,100,2000); q.enqueueScheduledEvent(EVENT_NOTE_OFF,60,0,2000); q.enqueueScheduledEvent(EVENT_NOTE_OFF,61,0,2000); q.enqueueScheduledEvent(EVENT_NOTE_OFF,62,0,2000); __test_millis=2000; ns.update(); assert(q.isEmpty()); assert(ns.getState()==STATE_IDLE); ns.stop(); q.enqueueScheduledEvent(EVENT_NOTE_ON,60,100,0xFFFFFFF0UL); __test_millis=0xFFFFFFF0UL; ns.update(); assert(ns.getState()==STATE_POSITIONING); ns.stop(); }

static void cc73_does_not_mutate_persistent_cfg(){ resetCfg(); uint8_t mode=cfg.airAttackMode; uint8_t off=cfg.airAttackOffset; AirflowController ac([](uint8_t,uint16_t,uint16_t){}); ac.setCC73Attack(100); assert(cfg.airAttackMode==mode); assert(cfg.airAttackOffset==off); assert(ac.runtimeAttackMode()==2); assert(ac.runtimeAttackOffset()>0); }
static void pca_detection_safe_boot(){ resetCfg(); extern WireClass Wire; extern int __pwm_write_count; __pwm_write_count=0; __digital_writes.clear(); Wire.clear(); InstrumentManager im0; assert(!im0.beginSafe()); assert(im0.hardwareInitStatus()==HW_PCA0_MISSING); assert(__digital_writes[PIN_SERVOS_OFF]==HIGH); assert(__pwm_write_count==0); Wire.setPresent(PCA_ADDR_BOARD0,true); InstrumentManager im1; assert(im1.beginSafe()); assert(im1.hardwareInitStatus()==HW_INIT_OK); assert(!im1.isSecondBoardEnabled()); im1.allSoundOff(); resetCfg(); cfg.fingers[0].pcaChannel=16; Wire.clear(); Wire.setPresent(PCA_ADDR_BOARD0,true); InstrumentManager im2; assert(!im2.beginSafe()); assert(im2.hardwareInitStatus()==HW_PCA1_MISSING); Wire.setPresent(PCA_ADDR_BOARD1,true); InstrumentManager im3; assert(im3.beginSafe()); assert(im3.isSecondBoardEnabled()); }
static void reservoir_autostart_behaviour(){ resetCfg(); extern WireClass Wire; Wire.clear(); Wire.setPresent(PCA_ADDR_BOARD0,true); cfg.airMode=AIR_MODE_PUMP_RESERVOIR; cfg.sensorType=SENSOR_TYPE_HALL_KY024; cfg.reservoirAutoStart=true; cfg.reservoirTargetPercent=60; InstrumentManager im; assert(im.beginSafe()); assert(im.getPressureCtrl().getTargetPercent()==60); im.allSoundOff(); assert(im.getPressureCtrl().getTargetPercent()==0); resetCfg(); Wire.clear(); Wire.setPresent(PCA_ADDR_BOARD0,true); cfg.airMode=AIR_MODE_PUMP_RESERVOIR; cfg.sensorType=SENSOR_TYPE_TOF_VL53L0X; cfg.reservoirAutoStart=true; cfg.reservoirTargetPercent=60; InstrumentManager im2; assert(im2.beginSafe()); assert(im2.getPressureCtrl().getTargetPercent()==0); }

static void fan_autonomous(){ resetCfg(); __test_millis=0; cfg.airMode=AIR_MODE_FAN_SERVO; cfg.fanPin=26; cfg.fanMinPwm=60; cfg.fanMaxPwm=200; cfg.fanIdlePercent=20; cfg.fanIdleTimeoutMs=100; FanController f; f.begin(); f.onNoteOn(); f.setSpeed(50); __test_millis=300; f.update(); assert(__analog_writes[26]==130); f.onNoteOff(); __test_millis+=50; f.update(); assert(__analog_writes[26] < 130 && __analog_writes[26] > 0); __test_millis+=100; f.update(); __test_millis+=300; f.update(); assert(__analog_writes[26]==0); f.stop(); assert(__analog_writes[26]==0); }
static void midi_validation_edges(){ resetCfg(); cfg.numNotes=1; cfg.notes[0].midiNote=0; assert(validateAndNormalizeConfig(cfg,nullptr).valid); resetCfg(); cfg.numNotes=1; cfg.notes[0].midiNote=127; assert(validateAndNormalizeConfig(cfg,nullptr).valid); resetCfg(); cfg.numNotes=1; cfg.notes[0].midiNote=128; assert(!validateAndNormalizeConfig(cfg,nullptr).valid); resetCfg(); cfg.notes[0].midiNote=200; assert(!validateAndNormalizeConfig(cfg,nullptr).valid); resetCfg(); cfg.notes[0].midiNote=(uint8_t)-1; assert(!validateAndNormalizeConfig(cfg,nullptr).valid); resetCfg(); cfg.numNotes=2; cfg.notes[0].midiNote=60; cfg.notes[1].midiNote=60; assert(!validateAndNormalizeConfig(cfg,nullptr).valid); }
static void air_modes_paths(){ for(int mode=0; mode<=5; ++mode){ resetCfg(); cfg.airMode=mode; cfg.valveType=(mode==1); cfg.motorType=MOTOR_TYPE_PWM; int writes=0; AirflowController ac([&](uint8_t,uint16_t,uint16_t){writes++;}); ac.begin(); bool initiallySafe = !ac.isValveOpen() || mode==AIR_MODE_SERVO_ONLY || mode==AIR_MODE_FAN_SERVO; assert(initiallySafe); ac.setAirflowForNote(60,100); ac.openValve(); assert(ac.isValveOpen()); ac.closeValve(); assert(!ac.isValveOpen()); ac.setAirflowToRest(); assert(writes>0); } }
int main(){ pca_detection_safe_boot(); reservoir_autostart_behaviour(); cc73_does_not_mutate_persistent_cfg(); pressure_direct_pwm_once(); pressure_hall_pid_once_and_guards(); event_queue_cases(); note_sequencer_min_and_panic(); note_sequencer_monophonic_replacement(); fan_autonomous(); midi_validation_edges(); air_modes_paths(); std::cout << "behavior tests passed\n"; }
